import * as vscode from 'vscode'
import * as cp from 'child_process'
import * as path from 'path'

function run(cmd: string): string {
  try {
    return cp.execSync(cmd, { timeout: 5000, stdio: ['pipe', 'pipe', 'pipe'] }).toString().trim()
  } catch {
    return ''
  }
}

function check(cmd: string): boolean {
  return run(cmd) !== ''
}

export async function writeEnvironmentReport(workspaceFolders: readonly vscode.WorkspaceFolder[]): Promise<void> {
  if (!workspaceFolders || workspaceFolders.length === 0) return

  const lines: string[] = []
  const now = new Date().toISOString()

  // --- OS ---
  const platform = process.platform
  const osName = platform === 'win32' ? 'Windows' : platform === 'darwin' ? 'macOS' : 'Linux'
  const arch = process.arch

  // --- Python ---
  const py3 = run('python3 --version 2>&1') || run('python --version 2>&1')
  const pyCmd = check('python3 --version 2>&1') ? 'python3' : check('python --version 2>&1') ? 'python' : ''
  const hasPy = pyCmd !== ''

  // --- PDF libraries ---
  const hasFitz = hasPy && check(`${pyCmd} -c "import fitz" 2>&1 && echo ok`)
  const fitzVer = hasFitz ? run(`${pyCmd} -c "import fitz; print(fitz.__version__)"`) : ''
  const hasPlumber = hasPy && check(`${pyCmd} -c "import pdfplumber" 2>&1 && echo ok`)
  const hasPdfminer = hasPy && check(`${pyCmd} -c "import pdfminer" 2>&1 && echo ok`)

  // --- Image libraries ---
  const hasPillow = hasPy && check(`${pyCmd} -c "from PIL import Image" 2>&1 && echo ok`)
  const pillowVer = hasPillow ? run(`${pyCmd} -c "from PIL import __version__; print(__version__)"`) : ''
  const hasCV2 = hasPy && check(`${pyCmd} -c "import cv2" 2>&1 && echo ok`)

  // --- CLI tools ---
  const hasPdftotext = check('pdftotext -v 2>&1 && echo ok') || check('pdftotext --help 2>&1 && echo ok')
  const hasConvert = check('convert --version 2>&1 && echo ok')
  const hasMagick = check('magick --version 2>&1 && echo ok')
  const hasGhostscript = check('gs --version 2>&1 && echo ok') || check('gswin64c --version 2>&1 && echo ok')

  const ok = (v: boolean | string) => v ? '✅' : '❌'

  lines.push(`# NodeGraph — Agent Environment Report`)
  lines.push(``)
  lines.push(`> Auto-generated by the NodeGraph extension at activation.`)
  lines.push(`> **AI agents: read this file to understand what tools are available on this machine.**`)
  lines.push(`> Re-generated each time a \`.nodegraph.json\` file is opened.`)
  lines.push(``)
  lines.push(`Generated: \`${now}\``)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## System`)
  lines.push(``)
  lines.push(`| | |`)
  lines.push(`|---|---|`)
  lines.push(`| OS | ${osName} (\`${platform}\`) |`)
  lines.push(`| Architecture | \`${arch}\` |`)
  lines.push(`| Python | ${hasPy ? `${ok(true)} \`${py3}\`` : `${ok(false)} not found`} |`)
  lines.push(`| Python command | ${hasPy ? `\`${pyCmd}\`` : 'N/A'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## PDF Reading Capabilities`)
  lines.push(``)
  lines.push(`| Tool | Available | Notes |`)
  lines.push(`|------|:---------:|-------|`)
  lines.push(`| PyMuPDF (\`fitz\`) | ${ok(hasFitz)} | ${hasFitz ? `v${fitzVer} — recommended` : 'Install: \`pip install pymupdf\`'} |`)
  lines.push(`| pdfplumber | ${ok(hasPlumber)} | ${hasPlumber ? 'available' : 'Install: \`pip install pdfplumber\`'} |`)
  lines.push(`| pdfminer | ${ok(hasPdfminer)} | ${hasPdfminer ? 'available' : 'Install: \`pip install pdfminer.six\`'} |`)
  lines.push(`| poppler (\`pdftotext\`) | ${ok(hasPdftotext)} | ${hasPdftotext ? 'CLI tool available' : platform === 'win32' ? 'Install: download poppler for Windows' : platform === 'darwin' ? 'Install: \`brew install poppler\`' : 'Install: \`apt install poppler-utils\`'} |`)
  lines.push(`| Ghostscript (\`gs\`) | ${ok(hasGhostscript)} | ${hasGhostscript ? 'available' : 'optional'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Image Processing Capabilities`)
  lines.push(``)
  lines.push(`| Tool | Available | Notes |`)
  lines.push(`|------|:---------:|-------|`)
  lines.push(`| Pillow (\`PIL\`) | ${ok(hasPillow)} | ${hasPillow ? `v${pillowVer} — recommended` : 'Install: \`pip install Pillow\`'} |`)
  lines.push(`| OpenCV (\`cv2\`) | ${ok(hasCV2)} | ${hasCV2 ? 'available' : 'Install: \`pip install opencv-python\`'} |`)
  lines.push(`| ImageMagick (\`convert\`) | ${ok(hasConvert || hasMagick)} | ${(hasConvert || hasMagick) ? 'CLI tool available' : platform === 'win32' ? 'Install: imagemagick.org' : platform === 'darwin' ? 'Install: \`brew install imagemagick\`' : 'Install: \`apt install imagemagick\`'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Agent Recommendations`)
  lines.push(``)

  if (!hasPy) {
    lines.push(`> ⚠️ **Python not found.** PDF reading and image processing via Python are not available.`)
    lines.push(`> Install Python from https://python.org, then reopen a \`.nodegraph.json\` file to re-run this check.`)
    lines.push(``)
  }

  lines.push(`### Reading a PDF`)
  if (hasFitz) {
    lines.push(`Use PyMuPDF (recommended — fastest and most accurate):`)
    lines.push(`\`\`\`python`)
    lines.push(`import fitz`)
    lines.push(`doc = fitz.open("paper.pdf")`)
    lines.push(`text = "\\n".join(page.get_text() for page in doc)`)
    lines.push(`\`\`\``)
  } else if (hasPlumber) {
    lines.push(`Use pdfplumber:`)
    lines.push(`\`\`\`python`)
    lines.push(`import pdfplumber`)
    lines.push(`with pdfplumber.open("paper.pdf") as pdf:`)
    lines.push(`    text = "\\n".join(p.extract_text() or "" for p in pdf.pages)`)
    lines.push(`\`\`\``)
  } else if (hasPdftotext) {
    lines.push(`Use poppler CLI:`)
    lines.push(`\`\`\`bash`)
    lines.push(`pdftotext paper.pdf -`)
    lines.push(`\`\`\``)
  } else {
    lines.push(`❌ No PDF reading tool available. Ask the user to install PyMuPDF: \`pip install pymupdf\``)
  }

  lines.push(``)
  lines.push(`### Extracting images from a PDF`)
  if (hasFitz) {
    lines.push(`\`\`\`python`)
    lines.push(`import fitz`)
    lines.push(`doc = fitz.open("paper.pdf")`)
    lines.push(`for i, page in enumerate(doc):`)
    lines.push(`    for img in page.get_images():`)
    lines.push(`        xref = img[0]`)
    lines.push(`        pix = fitz.Pixmap(doc, xref)`)
    lines.push(`        pix.save(f"fig_{i}_{xref}.png")`)
    lines.push(`\`\`\``)
  } else if (hasPillow) {
    lines.push(`Pillow is available but cannot extract from PDF directly. Use PyMuPDF for extraction.`)
  } else {
    lines.push(`❌ No image extraction tool available.`)
  }

  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`*To refresh this report, reopen any \`.nodegraph.json\` file.*`)

  const report = lines.join('\n')

  for (const folder of workspaceFolders) {
    const agentDir = vscode.Uri.joinPath(folder.uri, '.agent')
    const outFile = vscode.Uri.joinPath(agentDir, 'ENVIRONMENT.md')
    try {
      await vscode.workspace.fs.createDirectory(agentDir)
      await vscode.workspace.fs.writeFile(outFile, Buffer.from(report, 'utf-8'))
    } catch {
      // silently ignore — workspace may be read-only
    }
  }
}
